# Generated by Django 4.2.6 on 2023-10-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoEstudiante',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('rut_al', models.CharField(default='0', max_length=50)),
                ('nom_al', models.CharField(max_length=50)),
                ('app_alumno', models.CharField(max_length=50)),
                ('apm_alumno', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
    ]
