# Generated by Django 4.2.7 on 2023-11-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoestudiante',
            name='uid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
