# Generated by Django 4.2.6 on 2023-11-10 20:12

import apps.estudiante.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_djangoestudiante_rut_al'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoestudiante',
            name='uid',
            field=apps.estudiante.models.VarcharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
