# Generated by Django 4.2.6 on 2023-11-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_alter_djangoestudiante_rut_al'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoestudiante',
            name='rut_al',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
