# Generated by Django 4.2.6 on 2023-11-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAula',
            fields=[
                ('cod_aula', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'aula',
                'verbose_name_plural': 'aulas',
            },
        ),
    ]
