# Generated by Django 4.2.6 on 2023-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoSolicitud',
            fields=[
                ('id_solicitud', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('rut_alumno', models.CharField(max_length=10)),
                ('rut_profesor', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(default=None, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('razon', models.CharField(max_length=500)),
                ('tipo_respuesta', models.IntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
            },
        ),
    ]
