# Generated by Django 4.2.6 on 2023-11-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangosolicitud',
            name='tema',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='djangosolicitud',
            name='razon',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
