# Generated by Django 4.2.6 on 2023-11-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_djangosolicitud_tema_alter_djangosolicitud_razon'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangosolicitud',
            name='id_asignatura',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='djangosolicitud',
            name='id_solicitud',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
