# Generated by Django 4.2.7 on 2023-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0003_alter_djangoasignatura_nom_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoasignatura',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
