# Generated by Django 4.2.7 on 2023-11-10 20:41

import apps.registro_estudiante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoRegistroEstudiante',
            fields=[
                ('id_registro_estudiante', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('uid', apps.registro_estudiante.models.VarcharField()),
                ('id_asignatura', models.IntegerField(max_length=3)),
                ('cod_aula', models.CharField(max_length=10)),
                ('rut', models.CharField(max_length=10)),
                ('fecha_reg', models.DateField(default=None, null=True)),
                ('estado_reg', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'registro_estudiante',
                'verbose_name_plural': 'registros_estudiantes',
            },
        ),
    ]
