# Generated by Django 4.2.6 on 2023-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Docente'), ('3', 'Director de Carrera'), ('4', 'Secretario')], default='1', max_length=2),
        ),
    ]
