# Generated by Django 4.2.6 on 2023-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('sigla_asignatura', models.CharField(max_length=10)),
                ('seccion', models.CharField(max_length=10)),
            ],
        ),
    ]
