# Generated by Django 4.2.6 on 2023-10-18 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoRegistro',
            fields=[
                ('cod_registro', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('fecha_registro', models.DateTimeField(default=None, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.djangoestudiante')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
            },
        ),
    ]
