# Generated by Django 4.2.6 on 2023-10-18 02:49

import apps.registro.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_djangoregistro_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoregistro',
            name='uid',
            field=apps.registro.models.VarcharField(),
        ),
    ]
