# Generated by Django 4.2.6 on 2023-11-10 20:12

import apps.registro.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_djangoregistro_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoregistro',
            name='uid',
            field=apps.registro.models.VarcharField(),
        ),
    ]
