# Generated by Django 4.2.6 on 2023-11-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_djangoregistro_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoregistro',
            name='cod_aula',
        ),
        migrations.RemoveField(
            model_name='djangoregistro',
            name='estado_reg',
        ),
        migrations.RemoveField(
            model_name='djangoregistro',
            name='id_asignatura',
        ),
        migrations.RemoveField(
            model_name='djangoregistro',
            name='rut',
        ),
    ]
