# Generated by Django 4.2.7 on 2023-11-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_remove_djangoregistro_cod_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoregistro',
            name='fecha_reg',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
